sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t lincedin-appserver .
  - docker run -d -P lincedin-appserver
  - docker ps -a
  - docker run lincedin-appserver

script: 
  - make build
  - ./config/build/bin/RunUnitTests 

after_script: 
  - make doc

branches:
  only:
  - master
