sudo: required
dist: trusty

language: cpp

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5

services:
  - docker

before_install:
  - sudo apt-get install -y g++ make cmake doxygen graphviz python3-setuptools libsnappy-dev libleveldb-dev lcov libjansson-dev
  - sudo easy_install3 pip
  - docker build -t lincedin-appserver .
  - docker run -P lincedin-appserver sh -c "cd /root/LincedIn/LincedIn-TallerII-Server/; make test"
  - make clean
  
script: 
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++ 
  - gcc --version
  - make build

after_success:
  - make test

after_script: 
  - make doc

branches:
  only:
  - master
  - develop
