sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t lincedin-appserver .
  - docker run -d -P lincedin-appserver sh -c /root/LincedIn/LincedIn-TallerII-Server/config/build/bin/RunUnitTests
  - docker ps -a
  - docker run lincedin-appserver sh -c /root/LincedIn/LincedIn-TallerII-Server/config/build/bin/RunUnitTests


script: 
  - make build

after_success:
  - make test

after_script: 
  - make doc

branches:
  only:
  - master
