
elastic:  
  image: elasticsearch
  ports:
    - "9200:9200"
  volumes:
    - ./db/_elastic:/usr/share/elasticsearch/data
lincedin_appserver:  
  build: .
  volumes:
    - ./db:/root/LincedIn/LincedIn-TallerII-Server/db
  ports:
    - "8081:8081"
  expose:
    - "8081"
  links:
    - elastic